log_level = "INFO"
seed = 21122023

[project]
analysis_name = "pCosMx"  
data_type = "CosMx"
batch_key = "slide_id" 
sample_key = "sample_id"

[io]
base_dir = "."

[io.raw_data]
"Cos1380R387RRNA6K4u2716" = { dataset_dir = "data/set1/Cos1380R387RRNA6K4u2716", zarr_dir = "data/set1_zarrs/Cos1380R387RRNA6K4u2716.zarr"}
"Cos1400R355RRNA6K4u1716" = { dataset_dir = "data/set1/Cos1400R355RRNA6K4u1716", zarr_dir = "data/set1_zarrs/Cos1400R355RRNA6K4u1716.zarr"}


[pipeline]
modules = [
    "1_QualityControl",
    "1b_MergeData",
    "2_DimensionReduction",
    "3_Annotate",
    "4_ViewImages",
    "5_SpatialStat",
    "6_MuSpan",
    "7_Decoupler",
    "8_Cellphonedb",
    "8b_LIANA",
    "8c_LIANA_Causal",
    "9_DEAnalysis",
    "9b_GSEA",
    "10_WebVis",
]

[modules.MergeData]
# EMPTY! __main__.py will automatically find all folders inside analysis_pCosMx/1_QualityControl/

[modules.DimensionReduction]
# STANDARD SCANPY PIPELINE (No scvi-tools)
use_scviva = false
run_pca = true
n_comps = 50     
umap_latent = "X_pca"
n_neighbors = [15, 30]                    
resolution = [1.0]                
cluster_name = "leidenpca"

# Keep these in case you turn scVIVA back on later
scviva_layer = "counts"
scviva_spatial_knn = 10
scviva_epochs = 400
scvi_epochs = 400

[modules.Annotate]
chosen_cluster = "all" # Just an example, update based on output of Module 2
CellTypist_anno = false
CellTypist_train = false
ScType_anno = false

# Optional DE settings
[modules.Annotate.DE_params]
pval_adj = 0.05
logfoldchange = 1.0                # Stricter LFC
min_expr_frac = 0.20               # Relaxed expression fraction
specificity_margin = 0.15          # Stricter specificity
# junk_prefixes = ["MT-", "RPS", "RPL", "MALAT1", "XIST"] # Added XIST to junk genes

[modules.ViewImages]
chosen_cluster = "leidenpca_n15_r1.0"
gene_list = ["PIGR", "KRT8", "IGKC", "HLA-DRA", "LYZ", "IGHA1"]
embedding_key = "X_umap_n15_X_pca"
umap_color_columns = ["DiseaseType", "Inflammation"]

[modules.SpatialStat]
chosen_cluster = "leidenpca_n15_r1.0"
condition_key = "Inflammation"  # column in adata.obs with your conditions
reference_condition = "no"  # The baseline condition to subtract from others

[modules.MuSpan]
condition_key = "Inflammation"
reference_condition = "no"
chosen_cluster = "leidenpca_n15_r1.0"
transcripts = ["HLA-DRB", "KRT8", "TMSB4X", "TFF3", "IGHA1"]
min_edge_distance = 0
max_edge_distance = 10
distance_list = [1, 3, 5]
min_edge_distance_shape = 0
max_edge_distance_shape = 1
k_list = [2, 5, 10, 15]

selection_names = ["example"]
cell_types = ["1", "2"]

cellboundary_label = 'Cell boundaries' 
max_distance = 2
network_celltypes = ["0", "1", "2", "3", "4"]

[modules.MuSpan.selected_fovs]

"Cos1380R387RRNA6K4u2716_380R" = ["36","37", "38","39"]
"Cos1380R387RRNA6K4u2716_387R" = ["6", "7", "10", "11"]
"Cos1400R355RRNA6K4u1716_355R" = ["10", "11", "12", "13"]
"Cos1400R355RRNA6K4u1716_400R" = ["48", "49", "52", "53"]

[modules.Decoupler]
celltype_key = "leidenpca_n15_r1.0"
organism = "human"
grn = "dorothea"
dorothea_levels = ["A", "B"]

[modules.Cellphonedb]
microenv_resolution = 0.5
chosen_cluster = "leidenpca_n15_r1.0"
cpdb_version = 'v5.0.0'
human = true

target_sample = "Cos1380R387RRNA6K4u2716_380R" 

use_cellsign = false
celltypes = ["4", "5", "6"]
# target_genes = [
#     "IL6",      
#     "CXCR3",     
#     "CXCL9",      
#     "CXCL10",    
#     "CCL5",      
#     "IL1B",      
#     "IFNG",     
#     "IL22",      
# ]

[modules.LIANA]
bandwidth = 200
cutoff = 0.1
nz_prop = 0.05
n_nmf_components = 3
resource_name = 'consensus'

[modules.LIANA_Causal]
celltype_col = "leidenpca_n15_r1.0"
treatment_col = "Inflammation"
sample_key = "sample_id"
organism = "human"
solver = "HIGHS"      # 'CLARABEL', 'SCS', 'SCIP', 'SCIPY', 'HIGHS', 'OSQP'
expr_prop = 0.1
num_top_receptors = 10
num_top_tfs = 10
curation_effort = 5
node_cutoff = 0.1
max_runs = 20
stable_runs = 10

# Multiple Comparisons [Stim, Control]
comparisons = [
    ["yes", "no"],
]

# Multiple Cell Type Pairs [Source (Sender), Target (Receiver)]
cell_type_pairs = [
    ["1", "2"],
    ["2", "1"],
]

[modules.DEAnalysis]
DEAnalysis = true
celltype_col = "leidenpca_n15_r1.0"
treatment_col = "Inflammation"
comparisons = [
    ["yes", "no"],
]
pca_n_top_genes = 2000
pca_n_comps = 50

[modules.WebVisPrep]
annotation_columns = ["leiden", "leidenpca_n15_r1.0"]

# Explicitly define the target columns for the web UI here, instead of borrowing them
primary_annotation = "leidenpca_n15_r1.0"
microenv_col = "spatial_microenvironment"